### ISSUE TITLE
非常好的创意，星标支持一下！起点免费章节看不到本章说，设置了也无效，不知道是哪里的问题。

### ISSUE THREAD

**Issue by onlyoona** [NiaoBlush/novel-disguise#1]
非常好的创意，星标支持一下！起点免费章节看不到本章说，设置了也无效，不知道是哪里的问题。

**Comment by NiaoBlush** [comment]
@onlyoona 感谢支持，问题已经在 [1.4.1](https://github.com/NiaoBlush/novel-disguise/releases/tag/1.4.1)修复

**Comment by NiaoBlush** [comment]
![image](https://github.com/user-attachments/assets/7357ac04-5afd-4b4e-a08c-819bd846ed25)

**Comment by onlyoona** [comment]
非常感谢！
