### ISSUE TITLE
这个项目非常好评，作者大大可以支持一下wenku8.net,bilinovel.com吗

### ISSUE THREAD

**Issue by Oshibuki** [NiaoBlush/novel-disguise#2]
如题

**Comment by NiaoBlush** [comment]
感谢支持, 目前正在施工微信小说, 之后就看看这两个

**Comment by NiaoBlush** [comment]
@Oshibuki 已在[v1.5.0](https://github.com/NiaoBlush/novel-disguise/releases/tag/1.5.0)完成适配
~微信读书太难搞就先搞这两个了~

**Comment by NiaoBlush** [comment]
![image](https://github.com/user-attachments/assets/c7734541-b09f-4b7b-990b-641093aaf380)

![image](https://github.com/user-attachments/assets/30b61d61-03e7-48de-8849-dbaf37686572)
