### ISSUE TITLE
请问可以支持2k吗qwq

### ISSUE THREAD

**Issue by akane2333** [NiaoBlush/novel-disguise#3]
请问可以支持2k吗qwq，全屏的时候会拉伸，破绽太大了qwq

**Comment by NiaoBlush** [comment]
@akane2333 新版已经支持了, 之后`Excel`模式施工完毕后会一起发一版~

**Comment by NiaoBlush** [comment]
@akane2333 已在[v2.0.0]([img]./mon_202408/27/ekQ2u-gp5zZjT3cSsg-dm.png[/img]) 完成适配
