### ISSUE TITLE
大佬可以支持下飞卢吗

### ISSUE THREAD

**Issue by ssuunnsseett** [NiaoBlush/novel-disguise#4]
网址是这个https://www.faloo.com/
谢谢！

**Comment by NiaoBlush** [comment]
@ssuunnsseett 已在[v2.3.0](https://github.com/NiaoBlush/novel-disguise/releases/tag/2.3.0)适配飞卢
由于飞卢收费章节采用图片形式，只支持word模式

**Comment by NiaoBlush** [comment]
![image](https://github.com/user-attachments/assets/0522c473-42ab-44a8-88ca-4a1a06b01abc)
