### ISSUE TITLE
大佬能加网站嘛

### ISSUE THREAD

**Issue by fawaikuangtuwang5** [NiaoBlush/novel-disguise#5]
https://69shuba.cx/index.html
这个网站里面小说挺齐全的，主要是小说内容不会少，笔趣阁的小说内容总会少很多。

**Comment by NiaoBlush** [comment]
已在[v2.4.0](https://github.com/NiaoBlush/novel-disguise/releases/tag/2.4.0)完成适配
![image](https://github.com/user-attachments/assets/59e071d9-c6cf-4bee-8f6c-f34ade265d5b)

**Comment by Johanthan0415** [comment]
请求添加该网站的支持：https://www.ciweimao.com/
