### ISSUE TITLE
求新增Owlook网站

### ISSUE THREAD

**Issue by fawaikuangtuwang5** [NiaoBlush/novel-disguise#6]
网站地址：www.owlook.com.cn
该网站搜索小说较全，可以抓取多个网站内容在此网站观看小说。

**Comment by NiaoBlush** [comment]
已在[v2.5.0](https://github.com/NiaoBlush/novel-disguise/releases/tag/2.5.0)完成适配
![image](https://github.com/user-attachments/assets/3d439eb0-cab2-4fae-ac72-06a4b275b7ef)
